CREATE DATABASE nfl_model;
USE nfl_model;

CREATE TABLE teams(
	team_abbr VARCHAR(10) PRIMARY KEY,
    team_name VARCHAR(64) UNIQUE
);

CREATE TABLE team_stats_2022(
	team_abbr VARCHAR(10) PRIMARY KEY,
    points_for FLOAT,
    yards FLOAT,
    plays FLOAT,
    yards_per_play FLOAT,
    turnovers FLOAT,
    fumbles_lost FLOAT,
    first_downs FLOAT,
    completions FLOAT,
    pass_attempts FLOAT,
    pass_yards FLOAT,
    pass_tds FLOAT,
    interceptions FLOAT,
    pass_yards_per_attempt FLOAT,
    pass_first_downs FLOAT,
    rush_attempts FLOAT,
    rush_yards FLOAT,
    rush_tds FLOAT,
    rush_yards_per_attempt FLOAT,
    rush_first_downs FLOAT,
    penalties FLOAT,
    penalty_yards FLOAT,
    penalty_first_downs FLOAT,
    num_drives FLOAT,
    scoring_percentage FLOAT,
    turnover_percentage FLOAT,
		o_points_for FLOAT,
		o_yards FLOAT,
		o_plays FLOAT,
		o_yards_per_play FLOAT,
		o_turnovers FLOAT,
		o_fumbles_lost FLOAT,
		o_first_downs FLOAT,
		o_completions FLOAT,
		o_pass_attempts FLOAT,
		o_pass_yards FLOAT,
		o_pass_tds FLOAT,
		o_interceptions FLOAT,
		o_pass_yards_per_attempt FLOAT,
		o_pass_first_downs FLOAT,
		o_rush_attempts FLOAT,
		o_rush_yards FLOAT,
		o_rush_tds FLOAT,
		o_rush_yards_per_attempt FLOAT,
		o_rush_first_downs FLOAT,
		o_penalties FLOAT,
		o_penalty_yards FLOAT,
		o_penalty_first_downs FLOAT,
		o_num_drives FLOAT,
		o_scoring_percentage FLOAT,
		o_turnover_percentage FLOAT,
    3D_attempts FLOAT,
    3D_conversions FLOAT,
    3D_conversion_percentage FLOAT,
    4D_attempts FLOAT,
    4D_conversions FLOAT,
    4D_conversion_percentage FLOAT,
    red_zone_attempts FLOAT,
    red_zone_tds FLOAT,
    red_zone_td_percentage FLOAT,
        o_3D_attempts FLOAT,
		o_3D_conversions FLOAT,
		o_3D_conversion_percentage FLOAT,
		o_4D_attempts FLOAT,
		o_4D_conversions FLOAT,
		o_4D_conversion_percentage FLOAT,
		o_red_zone_attempts FLOAT,
		o_red_zone_tds FLOAT,
		o_red_zone_td_percentage FLOAT,
    CONSTRAINT team_stats_fk_teams FOREIGN KEY (team_abbr)
		REFERENCES teams (team_abbr)
		ON UPDATE CASCADE ON DELETE CASCADE
);