'''
Defining variables to be used in the web scraping process
'''

years = ['2010','2011','2012','2013','2014','2015','2016',
         '2017','2018','2019','2020','2021','2022']

team_abbr = ['crd', 'atl', 'rav', 'buf', 'car', 'chi', 'cin', 'cle', 
             'dal', 'den', 'det', 'gnb', 'htx', 'clt', 'jax', 'kan',
             'rai', 'sdg', 'ram', 'mia', 'min', 'nwe', 'nor', 'nyg', 
             'nyj', 'phi', 'pit', 'sfo', 'sea', 'tam', 'oti', 'was']

teams = {'Arizona Cardinals':'crd', 'Atlanta Falcons':'atl',
             'Baltimore Ravens':'rav', 'Buffalo Bills':'buf',
             'Carolina Panthers':'car', 'Chicago Bears':'chi',
             'Cincinnati Bengals':'cin', 'Cleveland Browns':'cle', 
             'Dallas Cowboys':'dal', 'Denver Broncos':'den',
             'Detroit Lions':'det', 'Green Bay Packers':'gnb',
             'Houston Texans':'htx', 'Indianapolis Colts':'clt',
             'Jacksonville Jaguars':'jax', 'Kansas City Chiefs':'kan',
             'Las Vegas Raiders':'rai','Oakland Raiders':'rai',
             'Los Angeles Chargers':'sdg', 'San Diego Chargers':'sdg',
             'Los Angeles Rams':'ram', 'St. Louis Rams':'ram',
             'Miami Dolphins':'mia','Minnesota Vikings':'min',
             'New England Patriots':'nwe', 'New Orleans Saints':'nor',
             'New York Giants':'nyg', 'New York Jets':'nyj',
             'Philadelphia Eagles':'phi', 'Pittsburgh Steelers':'pit',
             'San Francisco 49ers':'sfo', 'Seattle Seahawks':'sea',
             'Tampa Bay Buccaneers':'tam', 'Tennessee Titans':'oti',
             'Washington Commanders':'was','Washington Football Team':'was',
             'Washington Redskins':'was'}

columns = ['team_abbr',
    'points_for', 
    'yards', 
    'plays',
    'yards_per_plbay',
    'turnovers',
    'fumbles_lost',
    'first_downs' ,
    'completions',
    'pass_attempts',
    'pass_yards' ,
    'pass_tds',
    'interceptions',
    'pass_yards_per_attempt',
    'pass_first_downs',
    'rush_attempts',
    'rush_yards' ,
    'rush_tds' ,
    'rush_yards_per_attempt',
    'rush_first_downs',
    'penalties',
    'penalty_yards',
    'penalty_first_downs',
    'num_drives',
    'scoring_percentage',
    'turnover_percentage',
        'o_points_for',
        'o_yards',
        'o_plays',
        'o_yards_per_play',
        'o_turnovers',
        'o_fumbles_lost',
        'o_first_downs',
        'o_completions',
        'o_pass_attempts',
        'o_pass_yards',
        'o_pass_tds',
        'o_interceptions',
        'o_pass_yards_per_attempt',
        'o_pass_first_downs',
        'o_rush_attempts',
        'o_rush_yards',
        'o_rush_tds',
        'o_rush_yards_per_attempt',
        'o_rush_first_downs',
        'o_penalties',
        'o_penalty_yards',
        'o_penalty_first_downs',
        'o_num_drives',
        'o_scoring_percentage',
        'o_turnover_percentage',
    '3D_attempts',
    '3D_conversions',
    '3D_conversion_percentage',
    '4D_attempts',
    '4D_conversions',
    '4D_conversion_percentage',
    'red_zone_attempts',
    'red_zone_tds',
    'red_zone_td_percentage',
        'o_3D_attempts',
        'o_3D_conversions',
        'o_3D_conversion_percentage',
        'o_4D_attempts',
        'o_4D_conversions',
        'o_4D_conversion_percentage',
        'o_red_zone_attempts',
        'o_red_zone_tds',
        'o_red_zone_td_percentage']
