'''
Defining variables to be used in the web scraping process
'''
    
years = ['2010','2011','2012','2013','2014','2015','2016', '2017','2018', '2019','2020','2021','2022']

team_abbr = ['crd', 'atl', 'rav', 'buf', 'car', 'chi', 'cin', 'cle', 
             'dal', 'den', 'det', 'gnb', 'htx', 'clt', 'jax', 'kan',
             'rai', 'sdg', 'ram', 'mia', 'min', 'nwe', 'nor', 'nyg', 
             'nyj', 'phi', 'pit', 'sfo', 'sea', 'tam', 'oti', 'was']

teams = {'Arizona Cardinals':'crd', 'Atlanta Falcons':'atl',
             'Baltimore Ravens':'rav', 'Buffalo Bills':'buf',
             'Carolina Panthers':'car', 'Chicago Bears':'chi',
             'Cincinnati Bengals':'cin', 'Cleveland Browns':'cle', 
             'Dallas Cowboys':'dal', 'Denver Broncos':'den',
             'Detroit Lions':'det', 'Green Bay Packers':'gnb',
             'Houston Texans':'htx', 'Indianapolis Colts':'clt',
             'Jacksonville Jaguars':'jax', 'Kansas City Chiefs':'kan',
             'Las Vegas Raiders':'rai','Oakland Raiders':'rai',
             'Los Angeles Chargers':'sdg', 'San Diego Chargers':'sdg',
             'Los Angeles Rams':'ram', 'St. Louis Rams':'ram',
             'Miami Dolphins':'mia','Minnesota Vikings':'min',
             'New England Patriots':'nwe', 'New Orleans Saints':'nor',
             'New York Giants':'nyg', 'New York Jets':'nyj',
             'Philadelphia Eagles':'phi', 'Pittsburgh Steelers':'pit',
             'San Francisco 49ers':'sfo', 'Seattle Seahawks':'sea',
             'Tampa Bay Buccaneers':'tam', 'Tennessee Titans':'oti',
             'Washington Commanders':'was','Washington Football Team':'was',
             'Washington Redskins':'was'}

teams_wkly = {'Cardinals':'Arizona Cardinals', 'Falcons':'Atlanta Falcons',
             'Ravens':'Baltimore Ravens', 'Bills':'Buffalo Bills',
             'Panthers':'Carolina Panthers', 'Bears':'Chicago Bears',
             'Bengals':'Cincinnati Bengals', 'Browns':'Cleveland Browns', 
             'Cowboys':'Dallas Cowboys', 'Broncos':'Denver Broncos',
             'Lions':'Detroit Lions', 'Packers':'Green Bay Packers',
             'Texans':'Houston Texans', 'Colts':'Indianapolis Colts',
             'Jaguars':'Jacksonville Jaguars', 'Chiefs':'Kansas City Chiefs',
             'Raiders':'Las Vegas Raiders',
             'Chargers':'Los Angeles Chargers',
             'Rams':'Los Angeles Rams',
             'Dolphins':'Miami Dolphins','Vikings':'Minnesota Vikings',
             'Patriots':'New England Patriots', 'Saints':'New Orleans Saints',
             'Giants':'New York Giants', 'Jets':'New York Jets',
             'Eagles':'Philadelphia Eagles', 'Steelers':'Pittsburgh Steelers',
             '49ers':'San Francisco 49ers', 'Seahawks':'Seattle Seahawks',
             'Buccaneers':'Tampa Bay Buccaneers', 'Titans':'Tennessee Titans',
             'Commanders':'Washington Commanders','Football Team':'Washington Football Team',
             'Redskins':'Washington Redskins'}
        

teams_idx = {'crd':0, 'atl':1, 'rav':2, 'buf':3, 'car':4, 'chi':5, 'cin':6,
             'cle':7, 'dal':8, 'den':9, 'det':10, 'gnb':11, 'htx':12, 'clt':13,
             'jax':14, 'kan':15, 'rai':16, 'sdg':17, 'ram':18, 'mia':19,
             'min':20, 'nwe':21, 'nor':22, 'nyg':23, 'nyj':24, 'phi':25,
             'pit':26, 'sfo':27, 'sea':28, 'tam':29, 'oti':30, 'was':31}

columns = ['team_abbr',
    'points_for', 
    'yards', 
    'plays',
    'yards_per_play',
    'turnovers',
    'fumbles_lost',
    'first_downs' ,
    'completions',
    'pass_attempts',
    'pass_yards' ,
    'pass_tds',
    'interceptions',
    'pass_yards_per_attempt',
    'pass_first_downs',
    'rush_attempts',
    'rush_yards' ,
    'rush_tds' ,
    'rush_yards_per_attempt',
    'rush_first_downs',
    'penalties',
    'penalty_yards',
    'penalty_first_downs',
    'num_drives',
    'scoring_percentage',
    'turnover_percentage',
        'o_points_for',
        'o_yards',
        'o_plays',
        'o_yards_per_play',
        'o_turnovers',
        'o_fumbles_lost',
        'o_first_downs',
        'o_completions',
        'o_pass_attempts',
        'o_pass_yards',
        'o_pass_tds',
        'o_interceptions',
        'o_pass_yards_per_attempt',
        'o_pass_first_downs',
        'o_rush_attempts',
        'o_rush_yards',
        'o_rush_tds',
        'o_rush_yards_per_attempt',
        'o_rush_first_downs',
        'o_penalties',
        'o_penalty_yards',
        'o_penalty_first_downs',
        'o_num_drives',
        'o_scoring_percentage',
        'o_turnover_percentage',
    '3D_attempts',
    '3D_conversions',
    '3D_conversion_percentage',
    '4D_attempts',
    '4D_conversions',
    '4D_conversion_percentage',
    'red_zone_attempts',
    'red_zone_tds',
    'red_zone_td_percentage',
        'o_3D_attempts',
        'o_3D_conversions',
        'o_3D_conversion_percentage',
        'o_4D_attempts',
        'o_4D_conversions',
        'o_4D_conversion_percentage',
        'o_red_zone_attempts',
        'o_red_zone_tds',
        'o_red_zone_td_percentage']
        
weekly_columns = ['home_team',
    'away_team',
    'ht_points_for', 
    'ht_yards', 
    'ht_plays',
    'ht_yards_per_play',
    'ht_turnovers',
    'ht_fumbles_lost',
    'ht_first_downs' ,
    'ht_completions',
    'ht_pass_attempts',
    'ht_pass_yards' ,
    'ht_pass_tds',
    'ht_interceptions',
    'ht_pass_yards_per_attempt',
    'ht_pass_first_downs',
    'ht_rush_attempts',
    'ht_rush_yards' ,
    'ht_rush_tds' ,
    'ht_rush_yards_per_attempt',
    'ht_rush_first_downs',
    'ht_penalties',
    'ht_penalty_yards',
    'ht_penalty_first_downs',
    'ht_num_drives',
    'ht_scoring_percentage',
    'ht_turnover_percentage',
        'at_points_for',
        'at_yards',
        'at_plays',
        'at_yards_per_play',
        'at_turnovers',
        'at_fumbles_lost',
        'at_first_downs',
        'at_completions',
        'at_pass_attempts',
        'at_pass_yards',
        'at_pass_tds',
        'at_interceptions',
        'at_pass_yards_per_attempt',
        'at_pass_first_downs',
        'at_rush_attempts',
        'at_rush_yards',
        'at_rush_tds',
        'at_rush_yards_per_attempt',
        'at_rush_first_downs',
        'at_penalties',
        'at_penalty_yards',
        'at_penalty_first_downs',
        'at_num_drives',
        'at_scoring_percentage',
        'at_turnover_percentage',
    'ht_3D_attempts',
    'ht_3D_conversions',
    'ht_3D_conversion_percentage',
    'ht_4D_attempts',
    'ht_4D_conversions',
    'ht_4D_conversion_percentage',
    'ht_red_zone_attempts',
    'ht_red_zone_tds',
    'ht_red_zone_td_percentage',
        'at_3D_attempts',
        'at_3D_conversions',
        'at_3D_conversion_percentage',
        'at_4D_attempts',
        'at_4D_conversions',
        'at_4D_conversion_percentage',
        'at_red_zone_attempts',
        'at_red_zone_tds',
        'at_red_zone_td_percentage']
    
final_columns = ['home_team',
    'away_team',
    'ht_points_for', 
    'ht_yards', 
    'ht_plays',
    'ht_yards_per_play',
    'ht_turnovers',
    'ht_fumbles_lost',
    'ht_first_downs' ,
    'ht_completions',
    'ht_pass_attempts',
    'ht_pass_yards' ,
    'ht_pass_tds',
    'ht_interceptions',
    'ht_pass_yards_per_attempt',
    'ht_pass_first_downs',
    'ht_rush_attempts',
    'ht_rush_yards' ,
    'ht_rush_tds' ,
    'ht_rush_yards_per_attempt',
    'ht_rush_first_downs',
    'ht_penalties',
    'ht_penalty_yards',
    'ht_penalty_first_downs',
    'ht_num_drives',
    'ht_scoring_percentage',
    'ht_turnover_percentage',
        'at_points_for',
        'at_yards',
        'at_plays',
        'at_yards_per_play',
        'at_turnovers',
        'at_fumbles_lost',
        'at_first_downs',
        'at_completions',
        'at_pass_attempts',
        'at_pass_yards',
        'at_pass_tds',
        'at_interceptions',
        'at_pass_yards_per_attempt',
        'at_pass_first_downs',
        'at_rush_attempts',
        'at_rush_yards',
        'at_rush_tds',
        'at_rush_yards_per_attempt',
        'at_rush_first_downs',
        'at_penalties',
        'at_penalty_yards',
        'at_penalty_first_downs',
        'at_num_drives',
        'at_scoring_percentage',
        'at_turnover_percentage',
    'ht_3D_attempts',
    'ht_3D_conversions',
    'ht_3D_conversion_percentage',
    'ht_4D_attempts',
    'ht_4D_conversions',
    'ht_4D_conversion_percentage',
    'ht_red_zone_attempts',
    'ht_red_zone_tds',
    'ht_red_zone_td_percentage',
        'at_3D_attempts',
        'at_3D_conversions',
        'at_3D_conversion_percentage',
        'at_4D_attempts',
        'at_4D_conversions',
        'at_4D_conversion_percentage',
        'at_red_zone_attempts',
        'at_red_zone_tds',
        'at_red_zone_td_percentage',
    'ht_score',
    'at_score',
    'total_points',
    'ht_pts_diff',
    'ht_vegas_line']
